[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-win7-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "linker=rust-lld"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "linker=rust-lld"]
