[package]
name = "hashp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros","rt-multi-thread","fs", "io-util"] }
futures = { version = "0.3" }
crossbeam-channel = "0.5"
sha2 = "0.10"
